# Generated by {{ config('app.name') }}
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://{{ $hostname }}:8443

LOG_CHANNEL=daily
DB_CONNECTION=mysql
DB_HOST=localhost
DB_PORT=3306
DB_DATABASE=stardust
DB_USERNAME=stardust
DB_PASSWORD="{{ $stardustPassword }}"

BROADCAST_DRIVER=pusher
CACHE_DRIVER=file
QUEUE_CONNECTION=database
SESSION_DRIVER=file
SESSION_LIFETIME=120